name: Build Zen Browser .deb Package

# This workflow now has TWO triggers
on:
  # 1. Trigger manually from the Actions tab
  workflow_dispatch:
    inputs:
      zen_version:
        description: 'Zen Browser version tag to build (e.g., v1.2.3)'
        required: true
        default: 'v1.2.3'
  
  # 2. Trigger automatically on every push to the main branch
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout THIS repository to get our packaging files
      - name: Checkout packaging repository
        uses: actions/checkout@v4

      # Step 2: Determine which version to build
      - name: Determine Version
        id: get_version
        run: |
          # If the workflow was triggered manually, use the provided input version.
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Using manual input version: ${{ github.event.inputs.zen_version }}"
            echo "ZEN_VERSION=${{ github.event.inputs.zen_version }}" >> $GITHUB_ENV
          # Otherwise (on a push), we'll build a "dev" package from the latest release.
          else
            echo "Push event detected. Fetching latest release tag for dev build."
            # Note: This requires the 'gh' CLI, which is pre-installed on runners.
            LATEST_TAG=$(gh release list --repo zen-browser/desktop --limit 1 --json tagName --jq '.[0].tagName')
            echo "Latest official release is ${LATEST_TAG}. Using it for dev build."
            echo "ZEN_VERSION=${LATEST_TAG}" >> $GITHUB_ENV
          fi

      # Step 3: Download and Extract the Official Zen Browser Release
      - name: Download and Extract Zen Browser
        run: |
          DOWNLOAD_URL="https://github.com/zen-browser/desktop/releases/download/${{ env.ZEN_VERSION }}/zen.linux-x86_64.tar.xz"
          
          echo "Downloading from ${DOWNLOAD_URL}"
          curl -L --fail -o zen-browser.tar.xz "${DOWNLOAD_URL}"
          
          echo "Extracting archive..."
          tar -xJvf zen-browser.tar.xz

      # Step 4: Prepare the packaging directory and set Debian version
      - name: Prepare Packaging Directory and Version
        run: |
          # Create a proper Debian version string. For pushes, add a timestamp.
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            DEB_VERSION=$(echo "${{ env.ZEN_VERSION }}" | sed 's/^v//')-1
          else
            # For pushes, create a unique dev version like 1.2.3-1~dev202310271430
            TIMESTAMP=$(date -u +%Y%m%d%H%M)
            DEB_VERSION=$(echo "${{ env.ZEN_VERSION }}" | sed 's/^v//')-1~dev${TIMESTAMP}
          fi
          echo "DEB_VERSION=${DEB_VERSION}" >> $GITHUB_ENV

          # Set up the staging directory
          STAGING_DIR="deb_dist/zen-browser_${DEB_VERSION}_amd64"
          echo "STAGING_DIR=${STAGING_DIR}" >> $GITHUB_ENV
          mkdir -p "${STAGING_DIR}"/{DEBIAN,opt/zen-browser,usr/bin,usr/share/applications,usr/share/icons/hicolor/256x256/apps}

      # Step 5: Create the Debian control file
      - name: Create Debian Control File
        run: |
          cat <<EOF > "${STAGING_DIR}/DEBIAN/control"
          Package: zen-browser
          Version: ${{ env.DEB_VERSION }}
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: A privacy-respecting, minimalist fork of Firefox.
          Depends: libgtk-3-0, libdbus-glib-1-2, libxt6
          EOF

      # Step 6: Assemble Files in Staging Directory
      - name: Assemble Files
        run: |
          mv zen/* "${STAGING_DIR}/opt/zen-browser/"
          ln -s /opt/zen-browser/zen "${STAGING_DIR}/usr/bin/zen-browser"
          cp packaging/zen.desktop "${STAGING_DIR}/usr/share/applications/"
          cp packaging/icons/zen-browser.png "${STAGING_DIR}/usr/share/icons/hicolor/256x256/apps/zen-browser.png"

      # Step 7: Build the final .deb package
      - name: Build the .deb Package
        run: |
          dpkg-deb --build "${STAGING_DIR}"
          mv "${STAGING_DIR}.deb" "zen-browser_${{ env.DEB_VERSION }}_amd64.deb"

      # Step 8: Upload .deb as a workflow artifact
      # We upload as an artifact because a 'push' event doesn't have a 'release' to attach to.
      - name: Upload .deb as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: ./zen-browser_${{ env.DEB_VERSION }}_amd64.deb
